Add: Managing all project under maven
bellshade/Java pull request #102
Opened 2022-03-14 13:57 UTC by OctavianCahyadi

# Deskripsi (Description)

- Masalah : ketika clone project setiap materi berdiri sendiri-sendiri tanpa classpath builder sehingga tidak bisa di run untuk setiap file *.java (di VSCODE). Untuk user baru mungkin akan kesulitan untuk mencoba running file *.java nya.
- Solusi : Management semua project di bawah maven build. Dengan maven ini semua repo project dari teman-teman semua yg berkontribusi bisa di buka dan di run dibawah maven builder. Jika project dibuka dengan VSCODE maka semua file .java yang ada main.class nya bisa di run.
- Menambahkan wrapperclasses (baru Integer)

# Checklist:
##### Umum:
- [ ✔️ ] Saya menambah algoritma terbaru.
- [ ✔️] Saya memperbaiki algoritma yang sudah ada.
- [ ✔️] Saya memperbaiki dokumentasi.
- [ ✔️] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [✔️] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/Java/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [✔️] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [✔️] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows 10``
- ``text Editor`` = ``VSCODE``
- ``java`` = ``openjdk version "17.0.2" 2022-01-18``
- ``maven``=``1mApache Maven 3.8.1``

2022-03-14 14:09 UTC, bhimsur commented
overall sudah bagus @OctavianCahyadi , sambil nunggu review yang lain juga, mungkin bisa ditambahkan untuk .gitignore nya agar folder hasil build tidak ikut naik ke repo, bisa refer ke [sini](https://github.com/github/gitignore/blob/main/Maven.gitignore)

2022-03-16 11:29 UTC, wahyuwiyoko commented
Jika ini diimplementasikan, ada baiknya update [README.md](https://github.com/bellshade/Java/blob/main/README.md) bagian **Panduan Penggunaan** untuk memberi tau user bisa menggunakan 2 teknik untuk run file Java, yaitu compile secara manual (CLI) dan auto compile di VSCode (menggunakan plugin dsb). Dan beberapa link direct perlu diubah (jika struktur direktori berubah).

Saran saya sebaiknya URL di README.md mengikuti standar tanda `/`. Contohnya saya cek URL direct jadi tercampur antara `/` dan `\`.
![firefox_6WENd5UT19](https://user-images.githubusercontent.com/68732241/158577421-fcc4b8b6-01cb-4451-9c87-92643d1ada5b.png)

Dan saya rasa untuk direktori tidak perlu diperpanjang karena _menumpuk_ seperti `src/main/java/com/bellshade`. Baiknya direktori dibuat sesimpel mungkin, contoh `src/java/bellshade` atau pun agar lebih mudah cukup `src/main` aja karena direktori di dalamnya sudah berisi `learn`, `algorithm`, dll. Kode program juga perlu diubah untuk package mengikuti direktori.

Dan juga update file [CONTRIBUTING.md](https://github.com/bellshade/Java/blob/main/CONTRIBUTING.md) untuk menambahkan persyaratan perubahan atau penambahan kode untuk kontributor yaitu kode **package** (contoh `package com.bellshade.algorithm.datastructure.Tree.BinaryTree;`).

Semua hanya saran dan pendapat saya. Sepenuhnya tergantung maintainer/tim Java untuk mengimplementasikannya.

2022-03-16 12:40 UTC, random-prog commented
boleh nih, apalagi PR ini bisa di blg revolusi besar"an dalam repo ini, mungkin kami minta membutuhkan waktu, dan untuk om @OctavianCahyadi mungkin bisa di lebih sederhana seperti yg di masukkan dari om @wahyuwiyoko 

Selain itu, kami akan mengubah syarat-syarat [CONTRIBUTING.md](https://github.com/bellshade/Java/blob/main/README.md) dan [README.md](https://github.com/bellshade/Java/blob/main/README.md). Baik terima kasih atas masukkannya ya om @wahyuwiyoko 😊🙏

2022-03-16 13:31 UTC, OctavianCahyadi commented
> boleh nih, apalagi PR ini bisa di blg revolusi besar"an dalam repo ini, mungkin kami minta membutuhkan waktu, dan untuk om @OctavianCahyadi mungkin bisa di lebih sederhana seperti yg di masukkan dari om @wahyuwiyoko 
> 
> Selain itu, kami akan mengubah syarat-syarat [CONTRIBUTING.md](https://github.com/bellshade/Java/blob/main/README.md) dan [README.md](https://github.com/bellshade/Java/blob/main/README.md). Baik terima kasih atas masukkannya ya om @wahyuwiyoko 😊🙏

Terimakasih om atas tanggapan dan sarannya 🙏

Baik nanti saya coba implementasikan masukan om @wahyuwiyoko

2022-03-16 14:00 UTC, bhimsur requested changes
folder target dan isinya mungkin bisa tidak ikut commit dan push ke repo

2022-03-17 01:51 UTC, OctavianCahyadi reviewed
sudah saya tambahkan di gitignore untuk 

target/
*/target/**

apakah harus di hapus dlu untuk folder target yg ada di repo ya @bhimsur  ?

2022-03-18 04:26 UTC, OctavianCahyadi commented
> folder target dan isinya mungkin bisa tidak ikut commit dan push ke repo

@bhimsur sudah saya hilangkan untuk target class sehingga tidak ikut ke push ke repo

> Dan saya rasa untuk direktori tidak perlu diperpanjang karena _menumpuk_ seperti `src/main/java/com/bellshade`. Baiknya direktori dibuat sesimpel mungkin, contoh `src/java/bellshade` atau pun agar lebih mudah cukup `src/main` aja karena direktori di dalamnya sudah berisi `learn`, `algorithm`, dll. Kode program juga perlu diubah untuk package mengikuti direktori.

> Saran saya sebaiknya URL di README.md mengikuti standar tanda `/`. Contohnya saya cek URL direct jadi tercampur antara `/` dan `\`.
> ![firefox_6WENd5UT19](https://user-images.githubusercontent.com/68732241/158577421-fcc4b8b6-01cb-4451-9c87-92643d1ada5b.png)

@wahyuwiyoko untuk mempersingkat direktori di maven project harus ada `src/main/java` baru setelah itu di ikuti direktori project. Jika `src/main/java` ini diubah, maven tidak bisa menemukan path project nya.

untuk standar  `/` di README.md sudah saya sesuaikan.

2022-03-18 09:00 UTC, wahyuwiyoko commented
Looks good to me @OctavianCahyadi :thumbsup:

2022-03-18 09:17 UTC, wahyuwiyoko requested changes
@OctavianCahyadi kalau bisa mungkin perlu ditambahkan dokumentasi 2 cara compile, manual dan di VSCode di [README.md](https://github.com/bellshade/Java/blob/main/README.md).

2022-03-19 07:09 UTC, random-prog commented
yep, jika sudah menambahkan hint compiling `README.md` dan packages di tiap folder untuk `CONTRIBUTING.md` bisa dilaporkan kesini ya, dan nantinya akan siap di merge... makasih

2022-03-19 16:24 UTC, bhimsur approved these changes

2022-03-21 09:13 UTC, OctavianCahyadi commented
> yep, jika sudah menambahkan hint compiling `README.md` dan packages di tiap folder untuk `CONTRIBUTING.md` bisa dilaporkan kesini ya, dan nantinya akan siap di merge... makasih

untuk README.md dan CONTRIBUTING.md sudah saya sesuaikan @random-prog

2022-03-21 09:17 UTC, OctavianCahyadi commented
unutk error di CommitCheck App ini kenapa ya ? saya check detail nya gak muncul error Auth 
![image](https://user-images.githubusercontent.com/22025254/159232966-01f4efcc-303a-45c6-bbaa-801b9863b452.png)

2022-03-21 10:27 UTC, wahyuwiyoko approved these changes
Looks good to me @OctavianCahyadi 👍 

Kalau PR ini di-merge, saya akan coba memperbaiki beberapa typo 😄

2022-03-21 12:18 UTC, random-prog commented
pesan commit nya om ga valid, coba commit ulg di bagian dokumentasi, dan jan lupa, utk dokumentasi disarankan utk tidak menggunakan nama dokumentasi, dan menggunaskan pesan _commit_ `docs` bukan `fix`

2022-03-21 13:10 UTC, slowy07 approved these changes
LGTM, request squash @bellshade/java-team

2022-03-22 13:05 UTC, random-prog commented
uhm, sebenarnya ini sdh komplit, syg aja `CommitMessages` nya failed, mungkin bisa comit lagi menggunakan `docs: <nama-pesan-commit>` nya, dan juga commit menggunakan `git commit -ammend`. lengkapnya [disini](https://www.atlassian.com/git/tutorials/rewriting-history). Dimohon segera memperbaiki git commit messages nya agar kami bisa merge pull request anda

terima kasih

2022-03-22 14:00 UTC, OctavianCahyadi commented
> uhm, sebenarnya ini sdh komplit, syg aja `CommitMessages` nya failed, mungkin bisa comit lagi menggunakan `docs: <nama-pesan-commit>` nya, dan juga commit menggunakan `git commit -ammend`. lengkapnya [disini](https://www.atlassian.com/git/tutorials/rewriting-history). Dimohon segera memperbaiki git commit messages nya agar kami bisa merge pull request anda
> 
> terima kasih

sudah saya ikuti tutorialnya kok tetap error ya di pesan commit nya :(

2022-03-22 16:29 UTC, slowy07 commented
![Screenshot_2022-03-22-11-28-22_1366x768](https://user-images.githubusercontent.com/40540262/159528174-f23224fe-1faa-4418-a0a1-9ce0f621e2cf.png)
green on latest commit @bellshade/java-team

2022-03-23 05:20 UTC, random-prog approved these changes
to the moon🚀🌑

2022-03-23 05:23 UTC, merged

2022-03-23 07:07 UTC, OctavianCahyadi commented
thank you all :)