fix: memperbaiki error package dan fungsi output
bellshade/Java pull request #108
Opened 2022-05-11 03:20 UTC by khairanabila

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ ] Saya menambah algoritma terbaru.
- [x] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/Java/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``OS`` = `Mac OS` 
- ``Java`` = ``18.0``

# Link Issues

Issues : #

2022-05-11 03:31 UTC, khairanabila commented
apakah ada bug dari compiler mavennya ??

https://stackoverflow.com/questions/14164386/maven-cannot-find-symbol-message-unhelpful

2022-05-11 13:39 UTC, bhimsur commented
cmiiw, karena pakai JDK versi 18, sedangkan pada file pom.xml untuk source dan target yang digunakan pada JDK versi 17, dan make sure aja versi java di maven nya sudah sesuai dengan JDK yang ingin digunakan (bisa pakai command `mvn --version`

2022-05-11 13:53 UTC, bhimsur requested changes
line 43, bisa disesuaikan ya variabel result nya

2022-05-16 02:55 UTC, random-prog reviewed
sdh bagus, tinggal kami approve dan squash merge, akan tetapi dikarenakan failing dalam repo, jdi kami tunda dlu sampai kami selesai memperbaiki masalah failing tersebut. terima kasih 🙏

2022-05-16 05:01 UTC, bhimsur approved these changes

2022-05-16 17:56 UTC, bhimsur requested changes
masih ada undefined variabel ya, bisa disesuaikan dulu

2022-06-13 01:43 UTC, closed without merging

2022-06-13 01:44 UTC, random-prog commented
maaf untuk skrg kami close dlu ya krn konfil, tapi jangan khawatir, kamu bisa _pull-request_ ulang. PR ini konflik diakibatkan penambahan repo sebelumnya, sehingga _crash_ dari branch ```main``` dan branch ```pull-request```. Terima kasih