Added m-coloring problem in Java using Backtracking
bellshade/Java pull request #141
Opened 2022-10-16 13:26 UTC by Akshat-Pandey16

# Deskripsi (Description)

# Checklist:
##### Umum:
- [#] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [#] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/Java/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [#] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using): Windows

- ``OS`` = `Windows` 
- ``Java`` = 'JDK 18' 

# Link Issues

Issues : #

2022-10-16 13:32 UTC, slowy07 commented
can you amend the message commit with following the rule ``CONTRIBUTING.md`` ?, thanks !

2022-10-16 14:42 UTC, random-prog requested changes
this good, but why you not add documentation like `README.md`? add on it, and then pls check again commit messages check, it's failing. fix it now

2022-10-16 14:53 UTC, random-prog reviewed
ohh yeah, once again, this just accpet the **INDONESIA LANGUAGES**!, i these are all braking rules, so i hope these all changes it to Bahasa Indonesia A.S.A.P! thank you :)

2022-10-17 07:09 UTC, random-prog commented
sorry, we close this PR cause you not change the commit messages, not add documentationn (`README.md`) and not follow our contrib rules

2022-10-17 07:09 UTC, closed without merging